try{
jQuery(window).on('load',function(){var carousels=jQuery('.carousel');carousels.each(function(){var carousel=jQuery(this);var carouselID=carousel.attr('data-gallery-id');var itemsPerPage=parseInt(carousel.attr('data-pager'));var carouselControls=carousel.attr('data-controls');var carouselControlNav=!0;var carouselDirectionNav=!1;var carouselSlideshow=carousel.attr('data-slideshow');var carouselSpeed=carousel.attr('data-gallery-speed');var carouselSlides=carousel.find('.slide');carouselSlideshow=carouselSlideshow!=undefined?!0:!1;carouselSpeed=carouselSpeed==undefined?7000:parseInt(carouselSpeed);switch(carouselControls){case 'paging':carouselControlNav=!0;carouselDirectionNav=!1;break;case 'direction':carouselControlNav=!1;carouselDirectionNav=!0;break;case 'both':carouselControlNav=!0;carouselDirectionNav=!0;break;case 'none':carouselControlNav=!1;carouselDirectionNav=!1;break}
if(carousel.parents('.tab-pane').not(':visible').length>0){var rowMargin=carousel.closest('.carousel-content.row').css('margin-left').replace(/-|px/gi,'');var slideWidth=Math.floor((carousel.closest('.tab-content').width()+parseInt(rowMargin*2))/itemsPerPage)}else{var slideWidth=Math.floor(carousel.closest('.carousel-content.row').width()/itemsPerPage)}
carouselSlides.css('min-width',slideWidth+'px');carousel.flexslider({animation:'slide',animationLoop:!0,multipleKeyboard:!0,itemWidth:slideWidth,itemMargin:0,minItems:itemsPerPage,maxItems:itemsPerPage,move:1,slideshow:carouselSlideshow,slideshowSpeed:carouselSpeed,controlsContainer:'.controls-'+carouselID,directionNav:carouselDirectionNav,controlNav:carouselControlNav,start:function(slider){slider.resize();if(!Modernizr.csstransforms){var controls=carousel.find('.carousel-controls');var controlsOffset=controls.outerWidth()/2;controls.css('margin-left','-'+controlsOffset+'px')}
fsnGalleryCarouselInitSliderAccessibility(slider)}})});var mobileCarousels=jQuery('.carousel-mobile');mobileCarousels.each(function(){var mobileCarousel=jQuery(this);var carouselControls=mobileCarousel.attr('data-controls');var carouselControlNav=!0;var carouselDirectionNav=!1;var carouselSlides=mobileCarousel.find('.slide');switch(carouselControls){case 'paging':carouselControlNav=!0;carouselDirectionNav=!1;break;case 'direction':carouselControlNav=!1;carouselDirectionNav=!0;break;case 'both':carouselControlNav=!0;carouselDirectionNav=!0;break;case 'none':carouselControlNav=!1;carouselDirectionNav=!1;break}
if(mobileCarousel.parents('.tab-pane').not(':visible').length>0){var rowMargin=mobileCarousel.closest('.carousel-content.row').css('margin-left').replace(/-|px/gi,'');var slideWidth=Math.floor((mobileCarousel.closest('.tab-content').width()+parseInt(rowMargin*2)))}else{var slideWidth=Math.floor(mobileCarousel.closest('.carousel-content.row').width())}
carouselSlides.css('min-width',slideWidth+'px');mobileCarousel.flexslider({animation:'slide',animationLoop:!1,multipleKeyboard:!0,itemWidth:slideWidth,itemMargin:0,minItems:1,maxItems:1,move:1,slideshow:!1,directionNav:carouselDirectionNav,controlNav:carouselControlNav,start:function(slider){slider.resize();fsnGalleryCarouselInitSliderAccessibility(slider)}})})});jQuery(window).on('resize',function(){var carousels=jQuery('.carousel');carousels.each(function(){var carousel=jQuery(this);var carouselSlides=carousel.find('.slide');var itemsPerPage=parseInt(carousel.attr('data-pager'));if(carousel.parents('.tab-pane').not(':visible').length>0){var rowMargin=carousel.closest('.carousel-content.row').css('margin-left').replace(/-|px/gi,'');var slideWidth=Math.floor((carousel.closest('.tab-content').width()+parseInt(rowMargin*2))/itemsPerPage)}else{var slideWidth=Math.floor(carousel.closest('.carousel-content.row').width()/itemsPerPage)}
carouselSlides.css('min-width',slideWidth+'px')});var mobileCarousels=jQuery('.carousel-mobile');mobileCarousels.each(function(){var mobileCarousel=jQuery(this);var carouselSlides=mobileCarousel.find('.slide');if(mobileCarousel.parents('.tab-pane').not(':visible').length>0){var rowMargin=mobileCarousel.closest('.carousel-content.row').css('margin-left').replace(/-|px/gi,'');var slideWidth=Math.floor((mobileCarousel.closest('.tab-content').width()+parseInt(rowMargin*2)))}else{var slideWidth=Math.floor(mobileCarousel.closest('.carousel-content.row').width())}
carouselSlides.css('min-width',slideWidth+'px')})});jQuery(document).ready(function(){if(!Modernizr.csstransforms){var tabsWithInvisibleCarousels=jQuery('.tab-pane').not(':visible').has('.carousel');tabsWithInvisibleCarousels.each(function(){var tab=jQuery(this);var tabID=tab.attr('id');jQuery('a[data-toggle="tab"][href="#'+tabID+'"]').on('shown.bs.tab',function(e){setTimeout(function(){var controls=jQuery(e.target.hash).find('.carousel-controls');var controlsOffset=controls.outerWidth()/2;controls.css('margin-left','-'+controlsOffset+'px')},10)})})}});function fsnGalleryCarouselInitSliderAccessibility(slider){if(slider.directionNav!==undefined){slider.directionNav.each(function(){jQuery(this).attr('role','button')})}
if(slider.controlNav!==undefined){slider.controlNav.each(function(){jQuery(this).attr('role','button')})}}
}catch(e){console.error("An error has occurred. [ File: https://www.scaramoucherestaurant.com/wp-content/plugins/fusion-extension-performance-optimizer/includes/js/fusion-extension-gallery.js?ver=1.7.2 ] [ "+e.stack+" ]");}