try{
jQuery(document).ready(function(){var mastheads=jQuery('.fsn-masthead');mastheads.each(function(){var masthead=jQuery(this);if(masthead.data('layout')==undefined){var viewportWidth=jQuery(window).width();if(viewportWidth>767){var header=jQuery('body').children('header').first();var headerPositioning=header.css('position');var headerHeight=header.outerHeight();if(headerHeight!==0&&(headerPositioning=='static'||headerPositioning=='relative')){fsnMastheadSetHeight(headerHeight,masthead);jQuery(window).on('resize.fsnMasthead',function(){var headerHeight=header.outerHeight();fsnMastheadSetHeight(headerHeight,masthead)})}}
if(jQuery('.masthead-item.video').length>0){fsnMastheadInitVideos(masthead)}
var mastheadSlider=masthead.find('.masthead-slider');if(mastheadSlider.length>0){fsnMastheadInitSlider(mastheadSlider)}}else{masthead.trigger('customInit.fsnMasthead')}})});function fsnMastheadSetHeight(headerHeight,masthead){var mastheadContainer=masthead.children('.masthead-container');var mastheadHeight=mastheadContainer.data('height');switch(mastheadHeight){case 'small':var heightPercentage='30';break;case 'medium':var heightPercentage='50';break;case 'large':var heightPercentage='70';break;case 'full':var heightPercentage='100';break;case 'custom':var heightPercentage=mastheadContainer.data('heightPercent');break}
mastheadContainer.css('height','calc('+heightPercentage+'vh - '+headerHeight+'px)')}
function fsnMastheadSetContentOffset(headerHeight){var mastheadContainer=jQuery('.fsn-masthead').children('.masthead-container');var mastheadContent=mastheadContainer.find('.masthead-item-content');mastheadContent.css('padding-top',headerHeight+'px')}
function fsnMastheadInitVideos(masthead){var pauseButtons=masthead.find('.masthead-item-video-pause');pauseButtons.on('click.fsnMasthead',function(){var pauseButton=jQuery(this);var video=pauseButton.prev('.masthead-item-video');var videoContainerId=video.attr('id');var videoContainer=document.getElementById(videoContainerId);if(pauseButton.hasClass('paused')){videoContainer.play();pauseButton.removeClass('paused').children('span').html(fsnExtMastheadL10n.video_pause)}else{videoContainer.pause();pauseButton.addClass('paused').children('span').html(fsnExtMastheadL10n.video_paused)}});if(window.matchMedia('(prefers-reduced-motion)').matches){var $videos=jQuery('.fsn-masthead .masthead-item-video');$videos.each(function(){var video=jQuery(this);var videoContainerId=video.attr('id');var videoContainer=document.getElementById(videoContainerId);var pauseButton=video.next('.masthead-item-video-pause');video.removeAttr('autoplay');videoContainer.pause();pauseButton.addClass('paused').children('span').html(fsnExtMastheadL10n.video_paused)})}
var mql=window.matchMedia('(min-width: 768px)');fsnMastheadMediaQueries(mql);mql.addListener(fsnMastheadMediaQueries)}
function fsnMastheadMediaQueries(e){if(e.matches){fsnMastheadVideoUpdate('desktop')}else{fsnMastheadVideoUpdate('mobile')}}
function fsnMastheadVideoUpdate(size){var $videos=jQuery('.fsn-masthead .masthead-item-video');$videos.each(function(){var video=jQuery(this);var videoContainerId=video.attr('id');var videoSourceId=video.children('source').attr('id');var videoContainer=document.getElementById(videoContainerId);var videoSource=document.getElementById(videoSourceId);var videoData=video.data('video-json');switch(size){case 'mobile':var posterSrc=videoData.mobile_poster_src;var videoSrc=videoData.mobile_src;break;case 'desktop':var posterSrc=videoData.desktop_poster_src;var videoSrc=videoData.desktop_src;break}
videoContainer.pause();videoContainer.setAttribute('poster',posterSrc);videoSource.setAttribute('src',videoSrc);videoContainer.load()})}
function fsnMastheadInitSlider(mastheadSlider){if(mastheadSlider.data('slideshow')!==undefined){var pauseButton=mastheadSlider.find('.masthead-slider-pause');pauseButton.on('click.fsnMasthead',function(){if(pauseButton.hasClass('paused')){mastheadSlider.flexslider('play');var $videos=mastheadSlider.find('.masthead-item-video');$videos.each(function(){var video=jQuery(this);var videoContainerId=video.attr('id');var videoContainer=document.getElementById(videoContainerId);videoContainer.play()});pauseButton.removeClass('paused').children('span').html(fsnExtMastheadL10n.video_pause)}else{mastheadSlider.flexslider('pause');var $videos=mastheadSlider.find('.masthead-item-video');$videos.each(function(){var video=jQuery(this);var videoContainerId=video.attr('id');var videoContainer=document.getElementById(videoContainerId);videoContainer.pause()});pauseButton.addClass('paused').children('span').html(fsnExtMastheadL10n.video_paused)}});if(window.matchMedia('(prefers-reduced-motion)').matches){var slideshow=!1;pauseButton.addClass('paused').children('span').html(fsnExtMastheadL10n.slider_paused)}else{var slideshow=!0}}else{var slideshow=!1}
var slideshowSpeed=mastheadSlider.data('slideshowSpeed')!==undefined?parseInt(mastheadSlider.data('slideshowSpeed')):7000;mastheadSlider.flexslider({selector:'.masthead-slides > li',animationSpeed:0,slideshow:slideshow,slideshowSpeed:slideshowSpeed,prevText:'Previous Item',nextText:'Next Item',start:function(slider){var incomingSlide=slider.find('.masthead-slides > li').eq(0);incomingSlide.addClass('animating-visible');fsnMastheadInitSliderAccessibility(slider)},before:function(slider){var incomingSlide=slider.find('.masthead-slides > li').eq(slider.animatingTo);incomingSlide.addClass('animating-visible');setTimeout(function(){if(slider.animatingTo===0){var outgoingSlideIndex=slider.last}else if(slider.animatingTo>0){var outgoingSlideIndex=parseInt(slider.animatingTo)-1}
var outgoingSlide=slider.find('.masthead-slides > li').eq(outgoingSlideIndex);outgoingSlide.removeClass('animating-visible')},600);fsnMastheadUpdateSliderAccessibility(slider)}})}
function fsnMastheadInitSliderAccessibility(slider){slider.directionNav.each(function(){jQuery(this).attr('role','button')});slider.controlNav.each(function(){jQuery(this).attr('role','button')});slider.controlNav.eq(0).append('<span class="sr-only">'+fsnExtMastheadL10n.current_slide+'</span>');slider.slides.not(':eq(0)').each(function(){jQuery(this).attr('aria-hidden',!0).find('.masthead-item-button, .masthead-item-video-pause').attr('tabindex','-1')})}
function fsnMastheadUpdateSliderAccessibility(slider){var incomingSlide=slider.find('.masthead-slides > li').eq(slider.animatingTo);slider.controlNav.not(':eq('+slider.animatingTo+')').find('.sr-only').remove();slider.controlNav.filter(':eq('+slider.animatingTo+')').append('<span class="sr-only">'+fsnExtMastheadL10n.current_slide+'</span>');slider.slides.not(':eq('+slider.animatingTo+')').each(function(){jQuery(this).attr('aria-hidden',!0).find('.masthead-item-button, .masthead-item-video-pause').attr('tabindex','-1')});incomingSlide.removeAttr('aria-hidden').find('.masthead-item-button, .masthead-item-video-pause').removeAttr('tabindex')}
}catch(e){console.error("An error has occurred. [ File: https://www.scaramoucherestaurant.com/wp-content/plugins/fusion-extension-masthead/includes/js/fusion-extension-masthead.js?ver=1.0.0 ] [ "+e.stack+" ]");}