try{
jQuery(document).ready(function(){jQuery('a[href*="#"]:not([href="#"]):not([data-toggle])').on('click',function(event){if(location.pathname.replace(/^\//,'')==this.pathname.replace(/^\//,'')&&location.hostname==this.hostname){var target=jQuery(this.hash);target=target.length?target:jQuery('[name="'+this.hash.slice(1)+'"]');if(target.length>0){var additionalOffset=jQuery('.locking-menu').length>0?jQuery('.locking-menu').outerHeight():0;if(jQuery('body').hasClass('admin-bar')){var offset=target.offset().top-additionalOffset-32}else{var offset=target.offset().top-additionalOffset}
var isSmoothScrollSupported='scrollBehavior' in document.documentElement.style;if(isSmoothScrollSupported){var scrollToOptions={top:offset,left:0,behavior:'smooth'};window.scroll(scrollToOptions)}else{jQuery('html, body').animate({scrollTop:offset},1000)}
return!1}}});jQuery(window).on('load',function(){var targetID=window.location.hash;var targetTabTrigger=jQuery('a[data-toggle="tab"][href="'+targetID+'"]');var targetModalTrigger=jQuery('a[data-toggle="modal"][href="'+targetID+'"]');if(targetTabTrigger.length>0){var additionalOffset=jQuery('.locking-menu').length>0?jQuery('.locking-menu').outerHeight():0;if(jQuery('body').hasClass('admin-bar')){var offset=targetTabTrigger.offset().top-additionalOffset-32}else{var offset=targetTabTrigger.offset().top-additionalOffset}
jQuery(window).scrollTop(offset);targetTabTrigger.trigger('click')}else if(targetModalTrigger.length>0){targetModalTrigger.first().trigger('click')}else if(targetID!=''){var target=jQuery(targetID);if(target.length>0){var additionalOffset=jQuery('.locking-menu').length>0?jQuery('.locking-menu').outerHeight():0;if(jQuery('body').hasClass('admin-bar')){var offset=target.offset().top-additionalOffset-32}else{var offset=target.offset().top-additionalOffset}
var isSmoothScrollSupported='scrollBehavior' in document.documentElement.style;if(isSmoothScrollSupported){var scrollToOptions={top:offset,left:0,behavior:'smooth'};window.scroll(scrollToOptions)}else{jQuery('html, body').animate({scrollTop:offset},1000)}
return!1}}})});jQuery(document).ready(function(){if(jQuery(window).width()<768){var body=jQuery('body');var viewportOffset=jQuery(window).height()/2;jQuery(window).on('resize.fsnADbase',function(){viewportOffset=jQuery(window).height()/2});var menuMobileFooter=jQuery('.fsn-menu.mobile_footer');jQuery(window).on('scroll.fsnADbase',function(){var scrollPosition=jQuery(window).scrollTop();if(scrollPosition>viewportOffset){menuMobileFooter.addClass('in')}else{menuMobileFooter.removeClass('in')}})}});jQuery(document).ready(function(){var icons=jQuery('.fsn-menu.inline.social a, .fsn-menu.inline.social button');icons.each(function(){var icon=jQuery(this);icon.prepend('<svg xmlns="http://www.w3.org/2000/svg" width="68" height="68" viewBox="0 0 68 68"><circle cx="34" cy="34" r="33" class="icon-circle-1" /><circle cx="34" cy="34" r="33" class="icon-circle-2" /></svg>')})});jQuery(document).ready(function(){if(jQuery(window).width()>768){var body=jQuery('body');var startPosition=200;var fixedButton=jQuery('#fixed-button');if(fixedButton.length>0){jQuery(window).on('scroll',function(){var scrollPosition=jQuery(window).scrollTop();if(scrollPosition>startPosition){fixedButton.addClass('in')}else{fixedButton.removeClass('in')}})}}});jQuery(document).ready(function(){jQuery('.scroll-indicator').on('click',function(event){var target=jQuery('#introduction');if(target.length>0){if(jQuery('body').hasClass('admin-bar')){var offset=target.offset().top-32}else{var offset=target.offset().top}
var isSmoothScrollSupported='scrollBehavior' in document.documentElement.style;if(isSmoothScrollSupported){var scrollToOptions={top:offset,left:0,behavior:'smooth'};window.scroll(scrollToOptions)}else{jQuery('html, body').animate({scrollTop:offset},1000)}
return!1}})})
}catch(e){console.error("An error has occurred. [ File: https://www.scaramoucherestaurant.com/wp-content/themes/fusion-scaramoucherestaurant/js/scripts.js?ver=5.8.2 ] [ "+e.stack+" ]");}